import { PlatformCredentialPort, PlatformCredentialRecord, PlatformProvider } from '@tce/contracts';
import { SupabaseClient } from '@supabase/supabase-js';
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

export class SupabaseCredentialAdapter implements PlatformCredentialPort {
  private readonly key: Buffer;
  constructor(private readonly db: SupabaseClient, encryptionKey: string) { this.key = Buffer.from(encryptionKey, 'base64'); if (this.key.length !== 32) throw new Error('Credential encryption key must be 32 bytes base64'); }
  private encrypt(value: Record<string, unknown>) { const iv = randomBytes(12), cipher = createCipheriv('aes-256-gcm', this.key, iv); const ciphertext = Buffer.concat([cipher.update(JSON.stringify(value), 'utf8'), cipher.final()]); return `${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${ciphertext.toString('base64')}`; }
  private decrypt(value: string): Record<string, unknown> { const [iv, tag, body] = value.split('.'); const decipher = createDecipheriv('aes-256-gcm', this.key, Buffer.from(iv, 'base64')); decipher.setAuthTag(Buffer.from(tag, 'base64')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(body, 'base64')), decipher.final()]).toString('utf8')) as Record<string, unknown>; }
  async list(userId: string) { const { data, error } = await this.db.from('platform_credentials').select('id,provider,environment,is_active').eq('user_id', userId).order('provider'); if (error) throw error; return (data ?? []).map((r) => ({ id: r.id, provider: r.provider as PlatformProvider, environment: r.environment, isActive: Boolean(r.is_active) })); }
  async get(userId: string, provider: PlatformProvider, environment = 'production') { const { data, error } = await this.db.from('platform_credentials').select('credentials_encrypted').eq('user_id', userId).eq('provider', provider).eq('environment', environment).eq('is_active', true).maybeSingle(); if (error) throw error; if (!data) throw new Error('Platform credentials not configured'); return this.decrypt(data.credentials_encrypted); }
  async save(userId: string, provider: PlatformProvider, environment: string, credentials: Record<string, unknown>) { const encrypted = this.encrypt(credentials); const { data, error } = await this.db.from('platform_credentials').upsert({ user_id: userId, provider, environment, credentials_encrypted: encrypted, encryption_version: 1, is_active: true }, { onConflict: 'user_id,provider,environment' }).select('id,provider,environment,is_active').single(); if (error) throw error; return { id: data.id, provider: data.provider as PlatformProvider, environment: data.environment, isActive: Boolean(data.is_active) }; }
  async remove(userId: string, provider: PlatformProvider, environment = 'production') { const { error } = await this.db.from('platform_credentials').update({ is_active: false }).eq('user_id', userId).eq('provider', provider).eq('environment', environment); if (error) throw error; }
}
