import { Auth, Board, Config, Data, Trading } from '@ssi.developer/ssi-sdk';
import { AccountBalance, AccountOrder, AccountPosition, BrokerPort, ConnectInput, ContractResult, PlatformHealth, SsiAuthInput, SsiConnectionPort, SsiConnectionTest } from '@tce/contracts';

export type SsiConfig = { apiKey: string; apiSecret: string; clientId?: string; privateKey?: string; accountNo: string };

export class SsiBrokerAdapter implements BrokerPort, SsiConnectionPort {
  readonly provider = 'ssi';
  private auth?: Auth;
  constructor(private readonly config: SsiConfig) {}
  private result<T>(fn: () => Promise<T>): Promise<ContractResult<T>> { return fn().then((data) => ({ ok: true, data }) as const).catch((error) => ({ ok: false, error: { code: 'PROVIDER_ERROR', message: error instanceof Error ? error.message : String(error), retryable: false, provider: this.provider } }) as const); }
  private createAuth() { return new Auth(new Config({ clientId: this.config.clientId ?? '', apiKey: this.config.apiKey, apiSecret: this.config.apiSecret, privateKey: this.config.privateKey ?? '', apiUrl: 'https://api.ssi.com.vn', streamingUrl: 'wss://stream.ssi.com.vn/ws/v3', timeout: 60000, maxRetries: 5, retryDelay: 2000, rateLimitPerSecond: 10 })); }
  private async authenticate(input: SsiAuthInput = {}) { this.auth ??= this.createAuth(); return input.transactionId ? this.auth.authenticate(undefined, input.transactionId) : this.auth.authenticate(input.otp); }
  async requestOtp() { return this.result(async () => { const auth = this.createAuth(); const result = await auth.requestOtp(); const data = (result?.data ?? {}) as Record<string, unknown>; return { message: String(data.message ?? 'SSI approval/OTP request sent'), transactionId: typeof data.transactionId === 'string' ? data.transactionId : undefined }; }); }
  async connect(_input: ConnectInput) { return this.result(async () => { await this.authenticate(); }); }
  async health(input: ConnectInput): Promise<ContractResult<PlatformHealth>> { const started = Date.now(); return this.result(async () => { if (!this.auth?.getToken()) await this.connect(input); return { provider: 'ssi', available: true, latencyMs: Date.now() - started, fetchedAt: new Date().toISOString() }; }); }
  async test(input: SsiAuthInput): Promise<ContractResult<SsiConnectionTest>> { return this.result(async () => { const token = await this.authenticate(input); const data = new Data(this.auth!); const securities = await data.marketData.getSecuritiesInfoByBoard(Board.HOSE); return { provider: 'ssi', apiVersion: 'v3', authentication: 'ok', marketData: 'ok', securities: securities.length, tokenExpiresAt: token?.expiresAt } as SsiConnectionTest; }); }
  private trading() { if (!this.auth) throw new Error('SSI is not connected'); return new Trading(this.auth); }
  async balance(accountNo: string) { return this.result(async () => { const b = await this.trading().portfolio.getEquityBalance(accountNo); return { cash: Number(b?.withdrawable ?? 0), equity: Number(b?.equity ?? 0), withdrawable: Number(b?.withdrawable ?? 0), source: 'ssi' } as AccountBalance; }); }
  async positions(accountNo: string) { return this.result(async () => (await this.trading().portfolio.getEquityPositions(accountNo) ?? []).map((p) => ({ symbol: String(p.symbol).toUpperCase(), quantity: Number(p.quantity ?? 0), averagePrice: Number(p.costPrice ?? 0), source: 'ssi' as const })) as AccountPosition[]); }
  async orders(accountNo: string) { return this.result(async () => (await this.trading().portfolio.getTodayOrders(accountNo) ?? []).filter((o) => o.orderId && o.symbol).map((o) => ({ externalId: String(o.orderId), symbol: String(o.symbol).toUpperCase(), side: String(o.side).toUpperCase() === 'S' ? 'SELL' as const : 'BUY' as const, quantity: Number(o.filledQuantity ?? o.quantity ?? 0), price: Number(o.avgPrice ?? o.price ?? 0), status: String(o.status ?? 'UNKNOWN'), createdAt: o.inputTime ? String(o.inputTime) : undefined, source: 'ssi' as const })) as AccountOrder[]); }
  async syncPortfolio(accountNo: string, input: SsiAuthInput) { const [balance, positions, orders] = await Promise.all([this.authenticate(input).then(() => this.balance(accountNo)), this.positions(accountNo), this.orders(accountNo)]); if (!balance.ok || !positions.ok || !orders.ok) return { ok: false, error: (!balance.ok ? balance : !positions.ok ? positions : orders).error } as const; return { ok: true, data: { positions: positions.data.filter((p) => p.quantity > 0), orders: orders.data.filter((o) => o.quantity > 0), balance: balance.data } } as const; }
  async disconnect(_input: ConnectInput) { this.auth = undefined; return { ok: true, data: undefined } as const; }
}
