'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { platformApi } from '../lib/api';
import { useAuthStore, useDashboardStore } from '../lib/store';

const tabs=['Overview','Positions','Recent Orders','Trading Platforms','Security'] as const;
type Tab=typeof tabs[number];
export default function Dashboard(){const router=useRouter();const {user,loading:initLoading,initialized,init,logout}=useAuthStore();const {data,loading,error,load}=useDashboardStore();const [tab,setTab]=useState<Tab>('Overview');const [platform,setPlatform]=useState<any>(null);const [environment,setEnvironment]=useState('testnet');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{init()},[init]);useEffect(()=>{if(initialized&&!user)router.replace('/login')},[initialized,user,router]);useEffect(()=>{if(user){load();const t=setInterval(load,30000);return()=>clearInterval(t)}},[user,load]);
 if(initLoading||!initialized||!user)return <main className="shell"><div className="card">Checking session…</div></main>;
 const positions=data?.positions??data?.currentPositions??[];const orders=data?.orders??data?.recentOrders??[];const pools=data?.pools??[];const next=data?.nextPositions??data?.candidates??[];const account=data?.account??{};
 const action=async(name:string,fn:()=>Promise<any>)=>{setBusy(name);setMessage('');try{const r=await fn();setMessage(`${name}: OK`);if(name==='Load SSI')setPlatform(r.data)}catch(e:any){setMessage(`${name}: ${e?.response?.data?.message??'Failed'}`)}finally{setBusy('')}};
 const platforms=tab==='Trading Platforms'?<div className="grid grid2"><div className="card"><h2>SSI FastConnect</h2><div className="field"><label>Environment</label><select value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="production">Production</option><option value="sandbox">Sandbox</option></select></div><div className="field"><input placeholder="Client ID" /><input placeholder="API Key" /><input placeholder="API Secret" type="password" /><input placeholder="Account No." /><input placeholder="Private Key" type="password" /></div><div className="actions"><button disabled={!!busy} onClick={()=>action('Save SSI',()=>platformApi.save('ssi',environment,{}))}>Save</button><button disabled={!!busy} onClick={()=>action('Test SSI',()=>platformApi.ssiTest({environment}))}>Test</button><button disabled={!!busy} onClick={()=>action('OTP',()=>platformApi.ssiOtp({environment}))}>Request OTP</button><button disabled={!!busy} onClick={()=>action('Load SSI',()=>platformApi.ssiCurrent({environment}))}>Current</button><button disabled={!!busy} onClick={()=>action('Sync SSI',()=>platformApi.ssiSync({environment}))}>Sync</button></div></div><Binance environment={environment} setEnvironment={setEnvironment} action={action}/></div>:null;
 return <main className="shell"><header className="row"><div><h1 style={{marginBottom:4}}>TCE Dashboard</h1><span className="muted">{user.email} · {account?.investedCapital!=null?`Investigate value / total: ${account.investedCapital}`:'Overview'}</span></div><button onClick={async()=>{await logout();router.replace('/login')}}>Sign out</button></header><nav className="nav">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>{message&&<p className={message.includes('Failed')?'error':'success'}>{message}</p>}{tab==='Overview'&&<><div className="grid grid4">{[['Backend','Online'],['Pools',pools.length],['Positions',positions.length],['Next',next.length]].map(([a,b])=><div className="card" key={String(a)}><div className="muted">{a}</div><strong>{String(b)}</strong></div>)}</div><div className="grid grid2" style={{marginTop:14}}><List title="Shared Pools" items={pools}/><List title="Next Positions" items={next}/></div></>}{tab==='Positions'&&<ListTable rows={positions} columns={['symbol','quantity','avgBuyCost','marketPrice','cycleNumber','unrealizedPnl']}/>} {tab==='Recent Orders'&&<ListTable rows={orders} columns={['side','symbol','quantity','price','status','fee','tax']}/>} {tab==='Trading Platforms'&&platforms}{tab==='Security'&&<div className="card"><h2>Security</h2><p>JWT is attached centrally by Axios. Expired access tokens are refreshed once. Refresh failure clears the session.</p><p className="muted">Credentials are submitted to the backend and are never rendered back from saved configuration.</p></div>}{loading&&<p className="muted">Refreshing…</p>}{error&&<p className="error">{error}</p>}</main>}
function List({title,items}:{title:string,items:any[]}){return <div className="card"><h2>{title}</h2>{items.length?items.map((x,i)=><div className="row" key={i}><span>{x.symbol??x.name??x.code??`#${i+1}`}</span><span>{x.price??x.targetPrice??''}</span></div>):<p className="muted">No data.</p>}</div>}
function ListTable({rows,columns}:{rows:any[],columns:string[]}){return <div className="card" style={{overflowX:'auto'}}><table className="table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{String(r?.[c]??'-')}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="muted">No data.</p>}</div>}
function Binance({environment,setEnvironment,action}:{environment:string;setEnvironment:(v:string)=>void;action:(n:string,f:()=>Promise<any>)=>void}){const [open,setOpen]=useState(true);return <div className="card"><div className="row"><h2>Binance Futures</h2><button onClick={()=>setOpen(!open)}>{open?'Collapse':'Expand'}</button></div>{open&&<><div className="field"><label>Environment</label><select value={environment==='sandbox'?'testnet':environment} onChange={e=>setEnvironment(e.target.value)}><option value="production">Production</option><option value="testnet">Testnet</option></select></div><p className="muted">API credentials and manual execution use the selected environment.</p><div className="field"><input placeholder="API Key" /><input placeholder="API Secret" type="password" /></div><div className="actions"><button onClick={()=>action('Save Binance',()=>platformApi.save('binance',environment,{}))}>Save</button><button onClick={()=>action('Test Binance',()=>platformApi.binanceTest(environment))}>Test</button></div><hr/><h3>Manual Entry</h3><div className="grid grid2"><input placeholder="Symbol"/><select><option>BUY</option><option>SELL</option></select><select><option>MARKET</option><option>LIMIT</option><option>STOP</option><option>STOP_MARKET</option></select><input placeholder="Quantity" type="number"/><input placeholder="Price (if applicable)" type="number"/><input placeholder="Trigger Price" type="number"/></div><div className="actions" style={{marginTop:10}}><button onClick={()=>action('Entry',()=>platformApi.binanceOrder({environment,symbol:'BTCUSDT',side:'BUY',type:'MARKET',quantity:0.001,positionSide:'BOTH'}))}>Send Entry</button><button onClick={()=>action('TP',()=>platformApi.binanceTp({environment,symbol:'BTCUSDT',side:'SELL',positionSide:'BOTH',quantity:0.001,triggerPrice:1}))}>TP</button><button onClick={()=>action('SL',()=>platformApi.binanceSl({environment,symbol:'BTCUSDT',side:'SELL',positionSide:'BOTH',quantity:0.001,triggerPrice:1}))}>SL</button></div></>}</div>}
