apiVersion: v1
kind: Namespace
metadata:
  name: tce
  labels:
    app.kubernetes.io/part-of: tce
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tce-quota
  namespace: tce
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
