apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tce-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: tce-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tce-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: tce-service
