import { Body, ConflictException, Controller, Delete, ForbiddenException, Get, Headers, Param, Patch, Post, Req, Res, ServiceUnavailableException, UnauthorizedException } from '@nestjs/common';
import { randomBytes } from 'node:crypto';
import type { Request, Response } from 'express';
import { isIP } from 'node:net';
import { AuthRepository } from './auth.repository';
import { AuthService } from './auth.service';
import { LoginDto, MfaLoginDto, MfaRecoveryDto, SignupDto } from './dto/auth.dto';
import { PasskeyService } from './passkey.service';
import { PostgresService } from './postgres.service';

const SESSION_COOKIE=process.env.AUTH_COOKIE_NAME||'__Secure-microfe_session';
const CSRF_COOKIE=process.env.AUTH_CSRF_COOKIE_NAME||'__Secure-microfe_csrf';
const COOKIE_DOMAIN=process.env.AUTH_COOKIE_DOMAIN||'.mrcute.space';

@Controller('auth')
export class AuthController {
 constructor(private readonly repo:AuthRepository,private readonly auth:AuthService,private readonly postgres:PostgresService,private readonly passkey:PasskeyService){}
 private cookie(header:string|undefined,name:string):string{for(const part of String(header||'').split(';')){const pos=part.indexOf('=');if(pos<0)continue;if(part.slice(0,pos).trim()===name){try{return decodeURIComponent(part.slice(pos+1).trim());}catch{return '';}}}return '';}
 private ip(req:Request):string|undefined{const raw=req.headers['x-forwarded-for'];const first=(Array.isArray(raw)?raw[0]:raw)?.split(',')[0]?.trim();return first&&isIP(first)?first:undefined;}
 private setCookies(res:Response,session:{token:string;csrfToken:string}):void{const domain=COOKIE_DOMAIN?'; Domain='+COOKIE_DOMAIN:'';const ttl=this.auth.sessionTtl();res.append('Set-Cookie',SESSION_COOKIE+'='+encodeURIComponent(session.token)+'; Max-Age='+ttl+'; Path=/; HttpOnly; Secure; SameSite=Lax'+domain);res.append('Set-Cookie',CSRF_COOKIE+'='+encodeURIComponent(session.csrfToken)+'; Max-Age='+ttl+'; Path=/; Secure; SameSite=Lax'+domain);}
 private clearCookies(res:Response):void{const domain=COOKIE_DOMAIN?'; Domain='+COOKIE_DOMAIN:'';res.append('Set-Cookie',SESSION_COOKIE+'=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax'+domain);res.append('Set-Cookie',CSRF_COOKIE+'=; Max-Age=0; Path=/; Secure; SameSite=Lax'+domain);}
 private async currentSession(req:Request){const token=this.cookie(req.headers.cookie,SESSION_COOKIE);if(!token)throw new UnauthorizedException({code:'AUTH_REQUIRED',message:'Authentication required'});const session=await this.repo.findSession(this.auth.hash(token));if(!session)throw new UnauthorizedException({code:'AUTH_REQUIRED',message:'Authentication required'});return {token,session};}
 private requireCsrf(req:Request,token:string,header:string|undefined):void{const csrfCookie=this.cookie(req.headers.cookie,CSRF_COOKIE);if(!this.auth.verifyCsrf(token,csrfCookie,header||''))throw new ForbiddenException({code:'CSRF_REQUIRED',message:'CSRF token required'});}
 @Get('status') async status(){const configured=this.postgres.configured&&Boolean(process.env.JWT_SECRET);if(!configured)return {configured:false,database:'not_configured',mfaConfigured:Boolean(process.env.MFA_ENCRYPTION_KEY),passkeyConfigured:Boolean(process.env.PASSKEY_RP_ID&&process.env.PASSKEY_ORIGIN)};try{await this.repo.checkDatabase();return {configured:true,database:'connected',mfaConfigured:Boolean(process.env.MFA_ENCRYPTION_KEY),passkeyConfigured:Boolean(process.env.PASSKEY_RP_ID&&process.env.PASSKEY_ORIGIN)};}catch{return {configured:true,database:'unavailable',mfaConfigured:Boolean(process.env.MFA_ENCRYPTION_KEY),passkeyConfigured:Boolean(process.env.PASSKEY_RP_ID&&process.env.PASSKEY_ORIGIN)};}}
 @Post('signup') async signup(@Body() body:SignupDto){try{const user=await this.auth.signUp(body.email.trim().toLowerCase(),body.password);if(!user)throw new ConflictException({code:'EMAIL_EXISTS',message:'Email already registered'});return {user:{id:user.id,email:user.email,role:user.role||'USER'}};}catch(error){if(error instanceof ConflictException)throw error;if((error as {code?:string})?.code==='23505')throw new ConflictException({code:'EMAIL_EXISTS',message:'Email already registered'});throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Unable to create account'});}}
 @Post('login') async login(@Body() body:LoginDto,@Req() req:Request,@Res({passthrough:true}) res:Response){try{const result=await this.auth.login(body.email.trim().toLowerCase(),body.password,this.ip(req),req.get('user-agent')||undefined);if(result.mfaRequired)return {code:'MFA_REQUIRED',mfaRequired:true,challenge:result.challenge,userId:result.userId};this.setCookies(res,result.session);return {user:{id:result.user.id,email:result.user.email,role:result.user.role||'USER'}};}catch(error){if(error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Authentication unavailable'});}}
 @Post('mfa/login') async mfaLogin(@Body() body:MfaLoginDto,@Req() req:Request,@Res({passthrough:true}) res:Response){try{const result=await this.auth.finishMfa(body.challenge,body.code,false,this.ip(req),req.get('user-agent')||undefined);this.setCookies(res,result.session);return {user:{id:result.user.id,email:result.user.email,role:result.user.role||'USER'}};}catch(error){if(error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'MFA verification unavailable'});}}
 @Post('mfa/recovery') async mfaRecovery(@Body() body:MfaRecoveryDto,@Req() req:Request,@Res({passthrough:true}) res:Response){try{const result=await this.auth.finishMfa(body.challenge,body.code,true,this.ip(req),req.get('user-agent')||undefined);this.setCookies(res,result.session);return {user:{id:result.user.id,email:result.user.email,role:result.user.role||'USER'}};}catch(error){if(error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'MFA recovery unavailable'});}}
 @Get('me') async me(@Req() req:Request){try{const {session}=await this.currentSession(req);await this.repo.touchSession(session.id);return {authenticated:true,user:{id:session.user!.id,email:session.user!.email,role:session.user!.role||'USER'}};}catch(error){if(error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Authentication unavailable'});}}
 @Post('refresh') async refresh(@Req() req:Request,@Res({passthrough:true}) res:Response,@Headers('x-csrf-token') csrfHeader?:string){const token=this.cookie(req.headers.cookie,SESSION_COOKIE);if(!token)throw new UnauthorizedException({code:'AUTH_REQUIRED',message:'Authentication required'});this.requireCsrf(req,token,csrfHeader);const nextToken=randomBytes(48).toString('base64url');try{await this.repo.rotateRefreshToken(this.auth.hash(token),this.auth.hash(nextToken),new Date(Date.now()+this.auth.sessionTtl()*1000),this.ip(req),req.get('user-agent')||undefined);}catch(error){if(error instanceof UnauthorizedException){this.clearCookies(res);throw error;}throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Unable to refresh session'});}this.setCookies(res,{token:nextToken,csrfToken:this.auth.csrfForSession(nextToken)});res.status(204);return undefined;}
 @Post('logout') async logout(@Req() req:Request,@Res({passthrough:true}) res:Response,@Headers('x-csrf-token') csrfHeader?:string){try{const token=this.cookie(req.headers.cookie,SESSION_COOKIE);if(token){const session=await this.repo.findSession(this.auth.hash(token));if(session){this.requireCsrf(req,token,csrfHeader);await this.repo.revokeSession(session.id);}}this.clearCookies(res);res.status(204);return undefined;}catch(error){if(error instanceof ForbiddenException||error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Unable to revoke session'});}}
 @Post('logout-all') async logoutAll(@Req() req:Request,@Res({passthrough:true}) res:Response,@Headers('x-csrf-token') csrfHeader?:string){try{const {token,session}=await this.currentSession(req);this.requireCsrf(req,token,csrfHeader);await this.repo.revokeAllSessions(session.user!.id);this.clearCookies(res);res.status(204);return undefined;}catch(error){if(error instanceof ForbiddenException||error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Unable to revoke sessions'});}}
 @Post('passkey/register/options') async passkeyRegisterOptions(@Req() req:Request,@Headers('x-csrf-token') csrfHeader?:string){const {token,session}=await this.currentSession(req);this.requireCsrf(req,token,csrfHeader);return this.passkey.registrationOptions(session.user!.id);}
 @Post('passkey/register/verify') async passkeyRegisterVerify(@Req() req:Request,@Headers('x-csrf-token') csrfHeader:string|undefined,@Body() body:unknown){const {token,session}=await this.currentSession(req);this.requireCsrf(req,token,csrfHeader);return this.passkey.registrationVerify(session.user!.id,body);}
 @Post('passkey/login/options') async passkeyLoginOptions(){return this.passkey.authenticationOptions();}
 @Post('passkey/login/verify') async passkeyLoginVerify(@Req() req:Request,@Body() body:unknown,@Res({passthrough:true}) res:Response){try{const result=await this.passkey.authenticationVerify(body,this.ip(req),req.get('user-agent')||undefined);if(result.mfaRequired)return {code:'MFA_REQUIRED',mfaRequired:true,challenge:result.challenge,userId:result.userId};this.setCookies(res,result.session);return {user:{id:result.user.id,email:result.user.email,role:result.user.role||'USER'}};}catch(error){if(error instanceof UnauthorizedException)throw error;throw new ServiceUnavailableException({code:'AUTH_DB_UNAVAILABLE',message:'Passkey authentication unavailable'});}}
 @Get('passkeys') async passkeys(@Req() req:Request){const {session}=await this.currentSession(req);return this.passkey.list(session.user!.id);}
 @Patch('passkeys/:id') async renamePasskey(@Req() req:Request,@Param('id') id:string,@Body() body:{friendlyName:string},@Headers('x-csrf-token') csrfHeader?:string){const {token,session}=await this.currentSession(req);this.requireCsrf(req,token,csrfHeader);return this.passkey.rename(session.user!.id,id,String(body?.friendlyName||''));}
 @Delete('passkeys/:id') async deletePasskey(@Req() req:Request,@Param('id') id:string,@Headers('x-csrf-token') csrfHeader?:string){const {token,session}=await this.currentSession(req);this.requireCsrf(req,token,csrfHeader);return this.passkey.remove(session.user!.id,id);}
}
