import { Injectable, UnauthorizedException } from '@nestjs/common';
import { SupabaseClientService } from './supabase-client.service';
export interface UserRow { id:string; email:string; password_hash:string; role:string; mfa_enabled:boolean; mfa_secret_encrypted:string|null; }
export interface SessionRow { id:string; user_id:string; token_hash:string; family_id:string; expires_at:string; revoked_at:string|null; user?:UserRow; }
@Injectable()
export class AuthRepository {
 constructor(private readonly supabase:SupabaseClientService){}
 async checkDatabase():Promise<void>{const a=await this.supabase.db.from('users').select('id',{head:true}).limit(1);if(a.error)throw a.error;const b=await this.supabase.db.from('refresh_sessions').select('id',{head:true}).limit(1);if(b.error)throw b.error;}
 async findUserByEmail(email:string):Promise<UserRow|null>{const {data,error}=await this.supabase.db.from('users').select('id,email,password_hash,role,mfa_enabled,mfa_secret_encrypted').eq('email',email.toLowerCase()).maybeSingle();if(error)throw error;return data as UserRow|null;}
 async findUserById(id:string):Promise<UserRow|null>{const {data,error}=await this.supabase.db.from('users').select('id,email,password_hash,role,mfa_enabled,mfa_secret_encrypted').eq('id',id).maybeSingle();if(error)throw error;return data as UserRow|null;}
 async createUser(email:string,passwordHash:string){const {data,error}=await this.supabase.db.from('users').insert({email:email.toLowerCase(),password_hash:passwordHash,role:'USER',mfa_enabled:false}).select('id,email,role,mfa_enabled').single();if(error)throw error;return data as {id:string;email:string;role:string;mfa_enabled:boolean};}
 async createSession(userId:string,tokenHash:string,familyId:string,expiresAt:Date,ip?:string,userAgent?:string):Promise<void>{const {error}=await this.supabase.db.from('refresh_sessions').insert({user_id:userId,token_hash:tokenHash,family_id:familyId,expires_at:expiresAt.toISOString(),ip:ip??null,user_agent:userAgent??null});if(error)throw error;}
 async findSession(tokenHash:string):Promise<SessionRow|null>{const {data,error}=await this.supabase.db.from('refresh_sessions').select('id,user_id,token_hash,family_id,expires_at,revoked_at').eq('token_hash',tokenHash).is('revoked_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(error)throw error;if(!data)return null;const user=await this.findUserById(data.user_id);if(!user)return null;return {...data,user} as SessionRow;}
 async touchSession(id:string):Promise<void>{const {error}=await this.supabase.db.from('refresh_sessions').update({last_used_at:new Date().toISOString()}).eq('id',id).is('revoked_at',null);if(error)throw error;}
 async rotateRefreshToken(tokenHash:string,newTokenHash:string,expiresAt:Date,ip?:string,userAgent?:string){const {data,error}=await this.supabase.db.rpc('rotate_refresh_token',{p_token_hash:tokenHash,p_new_token_hash:newTokenHash,p_new_expires_at:expiresAt.toISOString(),p_ip:ip??null,p_user_agent:userAgent??null});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new UnauthorizedException({code:'AUTH_REQUIRED',message:'Invalid refresh token'});if(row.reuse_detected)throw new UnauthorizedException({code:'REFRESH_TOKEN_REUSE',message:'Refresh token reuse detected'});return row as {user_id:string;role:string;new_session_id:string;reuse_detected:boolean};}
 async revokeSession(id:string):Promise<void>{const {error}=await this.supabase.db.from('refresh_sessions').update({revoked_at:new Date().toISOString(),last_used_at:new Date().toISOString()}).eq('id',id).is('revoked_at',null);if(error)throw error;}
 async revokeAllSessions(userId:string):Promise<void>{const {error}=await this.supabase.db.from('refresh_sessions').update({revoked_at:new Date().toISOString()}).eq('user_id',userId).is('revoked_at',null);if(error)throw error;}
 async consumeRecoveryCode(userId:string,codeHash:string):Promise<boolean>{const {data,error}=await this.supabase.db.rpc('consume_recovery_code',{p_user_id:userId,p_code_hash:codeHash});if(error)throw error;return data===true;}
}
