import { Injectable, BadRequestException, UnauthorizedException } from '@nestjs/common';
import { generateAuthenticationOptions, generateRegistrationOptions, verifyAuthenticationResponse, verifyRegistrationResponse } from '@simplewebauthn/server';
import { isoUint8Array } from '@simplewebauthn/server/helpers';
import { AuthRepository, UserRow } from './auth.repository';
import { AuthService, SessionMaterial } from './auth.service';
import { PasskeyRepository } from './passkey.repository';

const production=()=>process.env.NODE_ENV==='production';
@Injectable()
export class PasskeyService {
 constructor(private readonly passkeys:PasskeyRepository,private readonly users:AuthRepository,private readonly auth:AuthService){}
 private config(){const rpID=process.env.PASSKEY_RP_ID||(production()?'':'localhost');const origin=process.env.PASSKEY_ORIGIN||(production()?'':'http://localhost:5173');if(!rpID||!origin)throw new BadRequestException('Passkey is not configured');if(production()&&(rpID==='localhost'||origin.startsWith('http://localhost')))throw new BadRequestException('Passkey production domain is misconfigured');return {rpID,origin,rpName:process.env.PASSKEY_RP_NAME||'MRCute'};}
 async registrationOptions(userId:string){const {rpID,rpName}=this.config();const user=await this.users.findUserById(userId);if(!user)throw new UnauthorizedException();const existing=await this.passkeys.listForUser(userId);const options=await generateRegistrationOptions({rpName,rpID,userID:isoUint8Array.fromUTF8String(user.id),userName:user.email,userDisplayName:user.email,attestationType:'none',excludeCredentials:existing.map(c=>({id:c.credential_id,transports:c.transports as any})),authenticatorSelection:{residentKey:'required',userVerification:'required'}});await this.passkeys.createChallenge(userId,options.challenge,'registration');return options;}
 async registrationVerify(userId:string,response:any){const {rpID,origin}=this.config();if(!response?.response?.clientDataJSON)throw new BadRequestException('Invalid passkey response');let client:{challenge?:string};try{client=JSON.parse(Buffer.from(response.response.clientDataJSON,'base64url').toString('utf8')) as {challenge?:string};}catch{throw new BadRequestException('Invalid passkey client data');}if(!client.challenge)throw new UnauthorizedException('Invalid passkey challenge');const verified=await verifyRegistrationResponse({response,expectedChallenge:client.challenge,expectedOrigin:origin,expectedRPID:rpID,requireUserVerification:true});if(!verified.verified||!verified.registrationInfo)throw new UnauthorizedException('Passkey registration failed');const challenge=await this.passkeys.consumeChallenge(client.challenge,'registration');if(!challenge||challenge.user_id!==userId)throw new UnauthorizedException('Invalid, expired, or already-used passkey challenge');const credential=verified.registrationInfo.credential;return this.passkeys.createCredential({user_id:userId,credential_id:credential.id,public_key:Buffer.from(credential.publicKey).toString('base64url'),counter:credential.counter,transports:(credential.transports??response.response.transports??[]) as string[],friendly_name:'Passkey'});}
 async authenticationOptions(){const {rpID}=this.config();const options=await generateAuthenticationOptions({rpID,userVerification:'required',allowCredentials:[]});await this.passkeys.createChallenge(null,options.challenge,'authentication');return options;}
 async authenticationVerify(response:any,ip?:string,userAgent?:string):Promise<{mfaRequired:true;challenge:string;userId:string}|{mfaRequired:false;user:UserRow;session:SessionMaterial}>{const {rpID,origin}=this.config();const credentialId=response?.id||response?.rawId;if(typeof credentialId!=='string'||!response?.response?.clientDataJSON)throw new BadRequestException('Invalid passkey response');const credential=await this.passkeys.findByCredentialId(credentialId);if(!credential)throw new UnauthorizedException('Passkey not registered');const client=JSON.parse(Buffer.from(response.response.clientDataJSON,'base64url').toString('utf8')) as {challenge?:string};if(!client.challenge)throw new UnauthorizedException('Invalid passkey challenge');const challenge=await this.passkeys.consumeChallenge(client.challenge,'authentication');if(!challenge)throw new UnauthorizedException('Invalid or expired passkey challenge');const verified=await verifyAuthenticationResponse({response,expectedChallenge:client.challenge,expectedOrigin:origin,expectedRPID:rpID,credential:{id:credential.credential_id,publicKey:Buffer.from(credential.public_key,'base64url'),counter:Number(credential.counter),transports:credential.transports as any},requireUserVerification:true});if(!verified.verified)throw new UnauthorizedException('Passkey authentication failed');if (!(await this.passkeys.updateCredential(credential.id, Number(credential.counter), verified.authenticationInfo.newCounter, response.response.transports))) throw new UnauthorizedException('Passkey credential changed during authentication');const user=await this.users.findUserById(credential.user_id);if(!user)throw new UnauthorizedException();if(user.mfa_enabled)return {mfaRequired:true,challenge:await this.auth.issueMfaChallenge(user.id),userId:user.id};return {mfaRequired:false,user,session:await this.auth.createSession(user.id,ip,userAgent)};}
 async list(userId:string){return this.passkeys.listForUser(userId);}
 async rename(userId:string,id:string,name:string){const clean=name.trim().slice(0,80);if(!clean)throw new BadRequestException('Passkey name is required');await this.passkeys.rename(userId,id,clean);return {ok:true};}
 async remove(userId:string,id:string){await this.passkeys.remove(userId,id);return {ok:true};}
}
