'use client';

import { useEffect, useState } from 'react';
import { BINANCE_FUTURES_URLS } from '@tce/binance';
import { getCurrentSsiInfo, hasBinanceCredentials, hasSsiCredentials, placeBinanceOrder, placeBinanceSl, placeBinanceTp, requestSsiOtp, saveBinanceCredentials, saveSsiCredentials, syncSsiPortfolio, testBinanceConnection, testSsiConnection } from '../../services/platform';
import styles from './PlatformsPanel.module.css';

const emptySsi = { clientId: '', apiKey: '', apiSecret: '', privateKey: '', accountNo: '' };
const emptyBinance = { apiKey: '', apiSecret: '', baseUrl: '' };
const emptyOrder = { symbol: 'BTCUSDT', side: 'BUY', type: 'MARKET', quantity: '', price: '', triggerPrice: '', positionSide: 'BOTH', timeInForce: 'GTC' };

export default function PlatformsPanel() {
  const [saved, setSaved] = useState(false); const [binanceSaved, setBinanceSaved] = useState(false); const [ssi, setSsi] = useState(emptySsi); const [binance, setBinance] = useState(emptyBinance);
  const [environment, setEnvironment] = useState('production'); const [binanceEnvironment, setBinanceEnvironment] = useState('production'); const [otp, setOtp] = useState(''); const [transactionId, setTransactionId] = useState(''); const [status, setStatus] = useState(''); const [current, setCurrent] = useState(null); const [busy, setBusy] = useState(false); const [busyAction, setBusyAction] = useState('');
  const [order, setOrder] = useState(emptyOrder); const [tp, setTp] = useState(''); const [sl, setSl] = useState(''); const [orderResult, setOrderResult] = useState(null); const [confirmReal, setConfirmReal] = useState(false);
  useEffect(() => { let active = true; setCurrent(null); setTransactionId(''); setStatus(''); hasSsiCredentials(environment).then((a) => active && setSaved(a)).catch(() => active && setSaved(false)); return () => { active = false; }; }, [environment]);
  useEffect(() => { let active = true; setBinance((x) => ({ ...x, baseUrl: BINANCE_FUTURES_URLS[binanceEnvironment] })); hasBinanceCredentials(binanceEnvironment).then((a) => active && setBinanceSaved(a)).catch(() => active && setBinanceSaved(false)); return () => { active = false; }; }, [binanceEnvironment]);
  const message = (e, fallback) => e.response?.data?.message || e.message || fallback; const authBody = () => ({ environment, otp: otp || undefined, transactionId: transactionId || undefined });
  const button = (label, action, primary = false, name = '') => <button className={`${styles.button} ${primary ? styles.primary : ''}`} onClick={action} disabled={busy}>{busy && busyAction === name ? 'Working…' : label}</button>;
  const run = async (name, fn, done) => { setBusy(true); setBusyAction(name); setStatus('Working…'); try { done(await fn()); } catch (e) { setStatus(message(e, 'Request failed.')); } finally { setBusy(false); setBusyAction(''); } };
  const setS = (k,v) => setSsi((x) => ({...x,[k]:v})); const setB = (k,v) => setBinance((x) => ({...x,[k]:v})); const setO = (k,v) => setOrder((x) => ({...x,[k]:v}));
  const saveSsi = () => run('ssi-save', async () => { if (!ssi.apiKey || !ssi.apiSecret || !ssi.accountNo) throw new Error('SSI API Key, API Secret and Account No. are required.'); await saveSsiCredentials(environment, ssi); return true; }, () => { setSaved(true); setStatus('SSI credentials saved.'); });
  const saveB = () => run('binance-save', async () => { if (!binance.apiKey || !binance.apiSecret) throw new Error('Binance API Key and API Secret are required.'); await saveBinanceCredentials(binanceEnvironment, {...binance, baseUrl: BINANCE_FUTURES_URLS[binanceEnvironment]}); return true; }, () => { setBinanceSaved(true); setStatus(`Binance ${binanceEnvironment === 'testnet' ? 'Testnet' : 'Production'} credentials saved securely.`); });
  const testB = () => run('binance-test', () => testBinanceConnection(binanceEnvironment), (r) => setStatus(`Binance connected • ${r?.environment || binanceEnvironment} • ${(r?.balances || []).length} balance rows.`));
  const testSsi = () => run('ssi-test', () => testSsiConnection({...authBody(), credentials:ssi}), (r) => setStatus(`SSI connected • API v${r?.apiVersion || '3'} • ${(r?.accounts || []).length} account(s). Order stream starts automatically.`));
  const requestOtp = () => run('otp', async () => { const r = await requestSsiOtp({environment, credentials:ssi}); const id = r?.data?.transactionId || r?.transactionId || ''; if (id) setTransactionId(id); return id; }, (id) => setStatus(id ? `SSI approval requested • ${id}` : 'SSI OTP / approval requested.'));
  const loadCurrent = () => run('current', () => getCurrentSsiInfo(authBody()), (r) => { setCurrent(r); setStatus('SSI current info loaded.'); });
  const sync = () => run('sync', () => syncSsiPortfolio(authBody()), (r) => setStatus(`Synced • ${r?.positionsSynced || 0} positions • ${r?.ordersSynced || 0} orders. Order stream active.`));
  const payload = () => ({...order, environment: binanceEnvironment, quantity:Number(order.quantity), price:order.price ? Number(order.price):undefined, triggerPrice:order.triggerPrice ? Number(order.triggerPrice):undefined});
  const sendOrder = () => run('order', () => { if (!confirmReal) throw new Error('Confirm the real-order checkbox first.'); if (!order.quantity || Number(order.quantity)<=0) throw new Error('Quantity must be greater than 0.'); if (order.type==='LIMIT' && !order.price) throw new Error('Limit price is required.'); return placeBinanceOrder(payload()); }, (r) => {setOrderResult(r); setStatus(`Order ${r?.status || 'submitted'} • ${r?.orderId || ''}`);});
  const exitPayload = (triggerPrice) => ({environment:binanceEnvironment, symbol:order.symbol, side:order.side==='BUY'?'SELL':'BUY', positionSide:order.positionSide, quantity:Number(order.quantity), triggerPrice:Number(triggerPrice), reduceOnly:true});
  const sendTp = () => run('tp', () => { if (!confirmReal) throw new Error('Confirm the real-order checkbox first.'); if (!tp) throw new Error('TP trigger price is required.'); return placeBinanceTp(exitPayload(tp)); }, (r) => {setOrderResult(r); setStatus(`TP ${r?.status || 'submitted'} • ${r?.orderId || ''}`);});
  const sendSl = () => run('sl', () => { if (!confirmReal) throw new Error('Confirm the real-order checkbox first.'); if (!sl) throw new Error('SL trigger price is required.'); return placeBinanceSl(exitPayload(sl)); }, (r) => {setOrderResult(r); setStatus(`SL ${r?.status || 'submitted'} • ${r?.orderId || ''}`);});
  return <>
    <section className={`section page-section ${styles.page}`}><div className={styles.head}><div><span className="eyebrow">PLATFORM CONFIG</span><h2>SSI FastConnect</h2><small>Credentials stay server-side and are never returned.</small></div><span className={`${styles.status} ${saved?styles.statusOk:''}`}>{saved?'● CONFIGURED':'○ NOT CONFIGURED'}</span></div><div className={styles.fields}><label className={styles.field}>Environment<select className={styles.select} value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="production">Production</option><option value="sandbox">Sandbox</option></select></label><label className={styles.field}>Client ID<input className={styles.input} value={ssi.clientId} onChange={e=>setS('clientId',e.target.value)}/></label><label className={styles.field}>API Key<input className={styles.input} type="password" value={ssi.apiKey} onChange={e=>setS('apiKey',e.target.value)}/></label><label className={styles.field}>API Secret<input className={styles.input} type="password" value={ssi.apiSecret} onChange={e=>setS('apiSecret',e.target.value)}/></label><label className={styles.field}>Account No.<input className={styles.input} value={ssi.accountNo} onChange={e=>setS('accountNo',e.target.value)}/></label><label className={styles.field}>OTP<input className={styles.input} type="password" value={otp} onChange={e=>setOtp(e.target.value)}/></label></div><label className={styles.field}>Private Key<textarea className={styles.textarea} value={ssi.privateKey} onChange={e=>setS('privateKey',e.target.value)} rows={4}/></label><div className={styles.actions}>{button('Save SSI',saveSsi,true,'ssi-save')}{button('Test connection',testSsi,false,'ssi-test')}{button('Request OTP / Approval',requestOtp,false,'otp')}{button('Get current info',loadCurrent,false,'current')}{button('Sync portfolio',sync,false,'sync')}</div><div className={styles.note}><b>Auth state</b><span>{transactionId?`Transaction: ${transactionId} • `:''}{status||'Ready.'}</span></div>{current&&<pre className={styles.output}>{JSON.stringify(current,null,2)}</pre>}</section>
    <section className={`section page-section ${styles.page}`}><div className={styles.head}><div><span className="eyebrow">BINANCE FUTURES</span><h2>API Credentials</h2><small>USD-M Futures • environment controls endpoint automatically.</small></div><span className={`${styles.status} ${binanceSaved?styles.statusOk:''}`}>{binanceSaved?'● CONFIGURED':'○ NOT CONFIGURED'}</span></div><div className={styles.fields}><label className={styles.field}>Environment<select className={styles.select} value={binanceEnvironment} onChange={e=>setBinanceEnvironment(e.target.value)}><option value="production">Production</option><option value="testnet">Testnet</option></select></label><label className={styles.field}>API Key<input className={styles.input} type="password" value={binance.apiKey} onChange={e=>setB('apiKey',e.target.value)}/></label><label className={styles.field}>API Secret<input className={styles.input} type="password" value={binance.apiSecret} onChange={e=>setB('apiSecret',e.target.value)}/></label><label className={styles.field}>Base URL<input className={styles.input} value={BINANCE_FUTURES_URLS[binanceEnvironment]} readOnly/></label></div><div className={styles.actions}>{button('Save Binance',saveB,true,'binance-save')}{button('Test Binance connection',testB,false,'binance-test')}</div></section>
    <section className={`section page-section ${styles.page}`}><div className={styles.head}><div><span className="eyebrow">MANUAL EXECUTION</span><h2>Binance Futures Test Order</h2><small>Manual order form. Environment: {binanceEnvironment === 'testnet' ? 'Testnet' : 'Production'}.</small></div><span className={styles.status}>⚠ ORDER</span></div><div className={styles.fields}><label className={styles.field}>Symbol<input className={styles.input} value={order.symbol} onChange={e=>setO('symbol',e.target.value.toUpperCase())}/></label><label className={styles.field}>Side<select className={styles.select} value={order.side} onChange={e=>setO('side',e.target.value)}><option>BUY</option><option>SELL</option></select></label><label className={styles.field}>Order Type<select className={styles.select} value={order.type} onChange={e=>setO('type',e.target.value)}><option>MARKET</option><option>LIMIT</option><option>STOP</option><option>STOP_MARKET</option></select></label><label className={styles.field}>Quantity<input className={styles.input} type="number" min="0" step="any" value={order.quantity} onChange={e=>setO('quantity',e.target.value)}/></label>{(order.type==='LIMIT'||order.type==='STOP')&&<label className={styles.field}>Price<input className={styles.input} type="number" step="any" value={order.price} onChange={e=>setO('price',e.target.value)}/></label>}{(order.type==='STOP'||order.type==='STOP_MARKET')&&<label className={styles.field}>Trigger Price<input className={styles.input} type="number" step="any" value={order.triggerPrice} onChange={e=>setO('triggerPrice',e.target.value)}/></label>}<label className={styles.field}>Position Side<select className={styles.select} value={order.positionSide} onChange={e=>setO('positionSide',e.target.value)}><option>BOTH</option><option>LONG</option><option>SHORT</option></select></label>{order.type==='LIMIT'&&<label className={styles.field}>Time in Force<select className={styles.select} value={order.timeInForce} onChange={e=>setO('timeInForce',e.target.value)}><option>GTC</option><option>IOC</option><option>FOK</option></select></label>}<label className={styles.field}>Take Profit<input className={styles.input} type="number" step="any" value={tp} onChange={e=>setTp(e.target.value)} placeholder="Trigger price"/></label><label className={styles.field}>Stop Loss<input className={styles.input} type="number" step="any" value={sl} onChange={e=>setSl(e.target.value)} placeholder="Trigger price"/></label></div><label className={styles.note}><input type="checkbox" checked={confirmReal} onChange={e=>setConfirmReal(e.target.checked)}/> <b>I understand this submits a REAL Binance Futures order.</b><span>Use Testnet credentials when testing.</span></label><div className={styles.actions}>{button('Place entry order',sendOrder,true,'order')}{button('Place TP',sendTp,false,'tp')}{button('Place SL',sendSl,false,'sl')}</div>{orderResult&&<pre className={styles.output}>{JSON.stringify(orderResult,null,2)}</pre>}</section>
  </>;
}
