-- TCE corporate events collected from external market sources.
-- Run this migration in Supabase before enabling the cron job.

create table if not exists public.tce_corporate_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  ticker text not null,
  event_type text not null,
  ex_date date not null,
  execution_date date,
  content text,
  dividend_value numeric,
  source text not null default 'vietstock',
  source_url text,
  raw_data jsonb,
  scraped_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_tce_corporate_events_ticker
  on public.tce_corporate_events (ticker);

create index if not exists idx_tce_corporate_events_ex_date
  on public.tce_corporate_events (ex_date);

create index if not exists idx_tce_corporate_events_dividend
  on public.tce_corporate_events (event_type, dividend_value);

create or replace function public.set_tce_corporate_events_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tce_corporate_events_updated_at
  on public.tce_corporate_events;

create trigger trg_tce_corporate_events_updated_at
before update on public.tce_corporate_events
for each row execute function public.set_tce_corporate_events_updated_at();
