import { startAuthentication, startRegistration, browserSupportsWebAuthn } from '@simplewebauthn/browser';

// Auth always uses the same-origin API. Nginx proxies /api/* to NestJS.
const apiBase = '/api';
const token = () => localStorage.getItem('tce_access_token') || '';
const authHeaders = () => ({ Authorization:`Bearer ${token()}` });
async function request(path, options={}) { const response=await fetch(`${apiBase}${path}`,{...options,headers:{...(options.headers||{}),'Content-Type':'application/json'}}); const data=await response.json().catch(()=>({})); if(!response.ok)throw new Error(data.message||data.error||'Authentication request failed'); return data; }
function saveSession(session){if(!session?.accessToken)throw new Error('No access token returned');localStorage.setItem('tce_access_token',session.accessToken);if(session.refreshToken)localStorage.setItem('tce_refresh_token',session.refreshToken);}
function showError(message){const el=document.querySelector('#login-error');if(el)el.textContent=message;}

export function loginView(){const passkey=window.isSecureContext&&browserSupportsWebAuthn();return `<section class="auth-shell"><div class="auth-glow"></div><div class="auth-brand"><div class="brand-mark">T</div><div><span class="eyebrow">TCE</span><b>Treasury Cash Extraction</b></div></div><div class="auth-card"><div class="auth-header"><span class="auth-kicker">WELCOME BACK</span><h1>Sign in</h1><p>Access your trading workspace securely.</p></div><form id="login-form"><label>Email<input id="login-email" type="email" autocomplete="username webauthn" placeholder="you@example.com" required></label><label>Password<div class="password-wrap"><input id="login-password" type="password" autocomplete="current-password" placeholder="Enter your password" required><button type="button" class="password-toggle" id="toggle-password">Show</button></div></label><div class="auth-options"><label class="remember"><input id="remember-me" type="checkbox"> <span>Remember me</span></label><span class="secure-badge">● Backend secured</span></div><button class="auth-submit" type="submit"><span>Sign in</span><span>→</span></button>${passkey?'<button class="passkey-submit" id="passkey-login" type="button"><span>⌁</span><span>Sign in with Passkey</span></button>':''}<div id="login-error" class="auth-error" role="alert"></div></form><div class="auth-footer"><span>Protected TCE workspace</span><span>•</span><span>Backend Auth</span></div></div></section>`;}

export function bindLogin(){const form=document.querySelector('#login-form');if(!form)return;document.querySelector('#toggle-password')?.addEventListener('click',()=>{const input=document.querySelector('#login-password');const button=document.querySelector('#toggle-password');const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'Show':'Hide';});form.addEventListener('submit',async event=>{event.preventDefault();const submit=form.querySelector('.auth-submit');submit.disabled=true;submit.classList.add('loading');showError('');try{const data=await request('/auth/login',{method:'POST',body:JSON.stringify({email:document.querySelector('#login-email').value.trim(),password:document.querySelector('#login-password').value})});if(data.mfaRequired){localStorage.setItem('tce_mfa_user_id',data.userId);throw new Error('MFA verification is required.');}saveSession(data);location.href='/';}catch(error){showError(error.message||'Unable to sign in. Please try again.');submit.disabled=false;submit.classList.remove('loading');}});document.querySelector('#passkey-login')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;showError('');try{const options=await request('/auth/passkey/login/options',{method:'POST'});const response=await startAuthentication({optionsJSON:options});const data=await request('/auth/passkey/login/verify',{method:'POST',body:JSON.stringify(response)});if(data.mfaRequired){localStorage.setItem('tce_mfa_user_id',data.userId);throw new Error('MFA verification is required.');}saveSession(data);location.href='/';}catch(error){showError(error.name==='NotAllowedError'?'Passkey prompt was cancelled.':error.message||'Passkey sign-in failed.');button.disabled=false;}});}

export async function registerPasskey(){if(!token())throw new Error('Sign in before adding a passkey.');if(!window.isSecureContext||!browserSupportsWebAuthn())throw new Error('Passkey requires HTTPS and a supported browser.');const options=await request('/auth/passkey/register/options',{method:'POST',headers:authHeaders()});const response=await startRegistration({optionsJSON:options});return request('/auth/passkey/register/verify',{method:'POST',headers:authHeaders(),body:JSON.stringify(response)});}
export async function listPasskeys(){return request('/auth/passkeys',{headers:authHeaders()});}
export async function renamePasskey(passkeyId,friendlyName){return request(`/auth/passkeys/${encodeURIComponent(passkeyId)}`,{method:'PATCH',headers:authHeaders(),body:JSON.stringify({friendlyName})});}
export async function deletePasskey(passkeyId){return request(`/auth/passkeys/${encodeURIComponent(passkeyId)}`,{method:'DELETE',headers:authHeaders()});}
export async function refreshSession(){const refreshToken=localStorage.getItem('tce_refresh_token');if(!refreshToken)return false;try{const data=await request('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken})});saveSession(data);return true;}catch{clearSession();return false;}}
export function clearSession(){localStorage.removeItem('tce_access_token');localStorage.removeItem('tce_refresh_token');localStorage.removeItem('tce_mfa_user_id');}
