import './style.css';
import { platformSettingsView, bindPlatformSettings } from './platform-settings.js';
import { loginView, bindLogin } from './login.js';
import { signupView, bindSignup } from './signup.js';
import { securityView, bindSecurity } from './security.js';

const fallback={account:{initial_capital:0,cashout_realized:0,capital_deployed:0,capital_available:0,recovery_remaining:0,current_cycle:1},positions:[],orders:[],pools:[],nextPositions:[],candidates:[]};
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n||0),num=n=>Number(n||0).toLocaleString('vi-VN'),pct=(a,b)=>b?Math.round(a/b*100):0;
const routes=['/','/positions','/orders','/platforms','/security'],route=()=>window.location.pathname.replace(/\/+$/,'')||'/',token=()=>localStorage.getItem('tce_access_token')||'';
const apiBase='/api';
let backendStatus={ok:false,checking:true};
async function checkBackend(){try{const response=await fetch(`${apiBase}/auth/status`,{method:'GET',headers:{Accept:'application/json'},cache:'no-store'});const data=await response.json().catch(()=>({}));backendStatus={ok:response.ok&&data?.configured!==false,checking:false,...data};return backendStatus;}catch(error){backendStatus={ok:false,checking:false,error:error?.message||'Backend unavailable'};return backendStatus;}}
async function loadDashboard(){const response=await fetch(`${apiBase}/dashboard`,{headers:{Authorization:`Bearer ${token()}`,Accept:'application/json'},cache:'no-store'});const data=await response.json().catch(()=>({}));if(response.status===401){localStorage.removeItem('tce_access_token');localStorage.removeItem('tce_refresh_token');throw new Error('Session expired');}if(!response.ok)throw new Error(data.message||'Dashboard unavailable');return data;}
function backendBanner(){if(backendStatus.checking)return '<div class="backend-status checking">● Checking backend…</div>';if(!backendStatus.ok)return '<div class="backend-status down">● Backend unavailable — please try again</div>';return '<div class="backend-status up">● Backend online</div>';}
function positionActions(p){const id=String(p.id||p.symbol).replace(/[^a-zA-Z0-9_-]/g,'');return `<div class="position-actions" data-position-id="${id}"><button data-position-action="HOLD">Hold</button><button data-position-action="TAKE_PROFIT">Take profit</button><button data-position-action="CUT">Cut</button><button data-position-action="CASHOUT">Cash out</button></div>`;}
function bindPositionActions(){document.querySelectorAll('[data-position-action]').forEach(btn=>btn.addEventListener('click',()=>{const row=btn.closest('.position-wrap');const status=row?.querySelector('.position-action-status');if(status){status.textContent=`Action selected: ${btn.dataset.positionAction.replace('_',' ')}`;status.className='position-action-status selected';}row?.classList.toggle('expanded',false);}));}
async function load(){await checkBackend();const path=route();if(path==='/signup'){render(fallback,path);return}if(!backendStatus.ok){render(fallback,'/login');return}if(!token()){render(fallback,'/login');return}try{window.__tceData=await loadDashboard();await render(window.__tceData,path);}catch(error){if(error.message==='Session expired'){history.replaceState({},'','/login');render(fallback,'/login');return;}console.error(error);window.__tceData=fallback;await render(fallback,path);}}
function positionsView(d){const candidates=d.nextPositions||d.candidates||[];return `<section class="section page-section"><div class="section-head"><div><h2>Positions</h2><small>Your portfolio</small></div><span>${d.positions.length}</span></div><div class="cards">${d.positions.length?d.positions.map(p=>`<div class="position-wrap"><div class="position"><div><b>${p.symbol}</b><small>${p.quantity} cp • avg ${num(p.avg_cost)}</small></div><div class="right"><b>${money(p.market_value||p.cost_basis)}</b><small class="${(p.unrealized_pnl||0)>=0?'up':'down'}">${(p.unrealized_pnl||0)>=0?'+':''}${money(p.unrealized_pnl||0)}</small></div><button class="position-more" aria-label="Position actions" data-position-toggle>⋯</button></div><div class="position-actions-panel">${positionActions(p)}<span class="position-action-status">Choose an action</span></div></div>`).join(''):'<div class="empty">No open positions</div>'}</div></section><section class="section planned"><div class="section-head"><div><h2>Next 5 positions</h2><small>Shared buying candidates</small></div><span>${candidates.length}/5</span></div><div class="planned-list">${Array.from({length:5},(_,i)=>candidates[i]).map((c,i)=>c?`<div class="planned-row"><span class="slot">${c.rank}</span><div><b>${c.symbol}</b><small>${c.target_quantity?`${num(c.target_quantity)} cp`:''}${c.target_price?` • target ${num(c.target_price)}`:''}${c.reason?` • ${c.reason}`:''}</small></div><span class="planned-status">${c.status}</span></div>`:`<div class="planned-row"><span class="slot">${i+1}</span><div><b>Position ${i+1}</b><small>Waiting for shared candidate feed</small></div><span class="planned-status">Available</span></div>`).join('')}</div></section>`}
function ordersView(d){return `<section class="section page-section"><div class="section-head"><div><h2>Recent orders</h2><small>Your account only</small></div><span>${d.orders.length}</span></div><div class="orders">${d.orders.length?d.orders.map(o=>`<div class="order"><span class="badge ${o.side==='BUY'?'buy':'sell'}">${o.side}</span><b>${o.symbol}</b><span>${o.quantity} × ${num(o.price)}</span><strong>${money(o.gross_value)}</strong></div>`).join(''):'<div class="empty">No recent orders</div>'}</div></section>`}
function overviewView(d){const a=d.account,deployed=a.capital_deployed||0,target=a.cashout_target||30000000,recovered=a.cashout_realized||0;return `<section class="hero"><div><span>Account portfolio</span><strong>${money(deployed)}</strong><small>Your positions • P/L ${money(a.unrealized_pnl||0)}</small></div><div class="ring" style="--p:${pct(recovered,target)}%"><b>${pct(recovered,target)}%</b></div></section><section class="grid"><article><span>Đang triển khai</span><b>${money(deployed)}</b></article><article><span>Unrealized P/L</span><b>${money(a.unrealized_pnl||0)}</b></article><article><span>Open positions</span><b>${d.positions.length}</b></article><article><span>Max positions</span><b>${a.max_positions||2}</b></article></section><section class="section"><div class="section-head"><h2>Shared pools</h2><span>${(d.pools||[]).length}</span></div><div class="quick-links">${(d.pools||[]).slice(0,4).map(p=>`<button><b>${p.symbol}</b><span>${p.status||'ACTIVE'}</span></button>`).join('')||'<div class="empty">Shared pool feed is empty</div>'}</div></section><section class="section"><div class="section-head"><h2>Next positions</h2><span>Shared</span></div>${positionsView(d).split('<section class="section planned">')[1]?.replace(/<\/section>$/,'')||'<div class="empty">No shared candidates</div>'}</section>`}
async function render(d,path=route()){if(path==='/login'){document.querySelector('#app').innerHTML=`${backendBanner()}${loginView()}`;bindLogin();return}if(path==='/signup'){document.querySelector('#app').innerHTML=`${backendBanner()}${signupView()}`;bindSignup();return}if(!token()){history.replaceState({},'','/login');document.querySelector('#app').innerHTML=`${backendBanner()}${loginView()}`;bindLogin();return}const page=path==='/positions'?positionsView(d):path==='/orders'?ordersView(d):path==='/platforms'?await platformSettingsView():path==='/security'?await securityView():overviewView(d),active=path==='/'?0:path==='/positions'?1:path==='/orders'?2:path==='/platforms'?3:4;document.querySelector('#app').innerHTML=`${backendBanner()}<main><header><div><span class="eyebrow">TCE • TREASURY CASH EXTRACTION</span><h1>${path==='/positions'?'Positions':path==='/orders'?'Recent orders':path==='/platforms'?'Trading Platforms':path==='/security'?'Security':'Dashboard'}</h1></div><button class="live" id="logout">Sign out</button></header>${page}<nav>${[['⌂','Overview','/'],['◫','Positions','/positions'],['↕','Orders','/orders'],['⚙','Platforms','/platforms'],['◉','Security','/security']].map(([icon,label,to],i)=>`<button class="${i===active?'active':''}" data-route="${to}">${icon}<small>${label}</small></button>`).join('')}</nav></main>`;document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.route)));document.querySelector('#logout')?.addEventListener('click',()=>{localStorage.removeItem('tce_access_token');localStorage.removeItem('tce_refresh_token');history.replaceState({},'','/login');render(fallback,'/login')});document.querySelectorAll('[data-position-toggle]').forEach(el=>el.addEventListener('click',()=>el.closest('.position-wrap')?.classList.toggle('expanded')));bindPositionActions();if(path==='/platforms')bindPlatformSettings();if(path==='/security')bindSecurity()}
function navigate(to){if(!routes.includes(to))to='/';history.pushState({},'',''+to);render(window.__tceData||fallback,route())}window.addEventListener('popstate',()=>render(window.__tceData||fallback,route()));load();
