const apiBase='/api';

async function request(path, options={}) {
  const response=await fetch(`${apiBase}${path}`,{...options,headers:{...(options.headers||{}),'Content-Type':'application/json'}});
  const data=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(data.message||data.error||'Signup failed');
  return data;
}

function showError(message){const el=document.querySelector('#signup-error');if(el)el.textContent=message;}

export function signupView(){return `<section class="auth-shell"><div class="auth-glow"></div><div class="auth-brand"><div class="brand-mark">T</div><div><span class="eyebrow">TCE</span><b>Treasury Cash Extraction</b></div></div><div class="auth-card"><div class="auth-header"><span class="auth-kicker">CREATE ACCOUNT</span><h1>Sign up</h1><p>Create your TCE trading workspace account.</p></div><form id="signup-form"><label>Email<input id="signup-email" type="email" autocomplete="email" placeholder="you@example.com" required></label><label>Password<div class="password-wrap"><input id="signup-password" type="password" autocomplete="new-password" placeholder="At least 8 characters" minlength="8" required><button type="button" class="password-toggle" id="toggle-signup-password">Show</button></div></label><label>Confirm password<input id="signup-password-confirm" type="password" autocomplete="new-password" placeholder="Repeat your password" minlength="8" required></label><button class="auth-submit" type="submit"><span>Create account</span><span>→</span></button><div id="signup-error" class="auth-error" role="alert"></div></form><div class="auth-footer"><span>Already have an account?</span><a class="auth-link" href="/login">Sign in</a></div></div></section>`;}

export function bindSignup(){const form=document.querySelector('#signup-form');if(!form)return;document.querySelector('#toggle-signup-password')?.addEventListener('click',()=>{const input=document.querySelector('#signup-password');const button=document.querySelector('#toggle-signup-password');const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'Show':'Hide';});form.addEventListener('submit',async event=>{event.preventDefault();const submit=form.querySelector('.auth-submit');const email=document.querySelector('#signup-email').value.trim().toLowerCase();const password=document.querySelector('#signup-password').value;const confirm=document.querySelector('#signup-password-confirm').value;showError('');if(password!==confirm){showError('Passwords do not match.');return;}submit.disabled=true;submit.classList.add('loading');try{await request('/auth/signup',{method:'POST',body:JSON.stringify({email,password})});const session=await request('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('tce_access_token',session.accessToken);if(session.refreshToken)localStorage.setItem('tce_refresh_token',session.refreshToken);location.href='/';}catch(error){showError(error.message||'Unable to create account. Please try again.');submit.disabled=false;submit.classList.remove('loading');}});}
